import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/providers/transitionProvider";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";


const exo = Exo({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});



export const metadata: Metadata = {
  title: "Alvy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={exo.className}
      >
        <TransitionProvider>
          <Navbar />
          <Toaster />
          {children}
          <Footer />
        </TransitionProvider>
      </body>
    </html>
  );
}
